/*
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <https://www.gnu.org/licenses/>.
 */

#include "hardware/hardware.h"

#include "hpm_adc16_drv.h"
#include "hpm_clock_drv.h"
#include "hpm_dma_drv.h"
#include "hpm_dmamux_drv.h"
#include "hpm_ioc_regs.h"
#include "hpm_interrupt.h"
#include "hpm_l1c_drv.h"

// --------------------------------------------------------------------
// ADC Instance Selection
//
// Channels 0-15  -> HPM_ADC0 (PA00-PA07, PB00-PB07)
// Channels 16-31 -> HPM_ADC1 (PC00-PC07, PD00-PD07)
// Update if your board uses a different assignment.
// --------------------------------------------------------------------

#define HPM_ADC_INSTANCE_FOR_CH(ch) ((ch) < 16 ? HPM_ADC0 : HPM_ADC1)
#define HPM_ADC_LOCAL_CH(ch)        ((ch) < 16 ? (ch) : (ch) - 16)

// ADC DMA result word format (HPM ADC16 sequence result):
//   bits [15:0]  = 16-bit ADC result
//   bits [20:16] = channel number in sequence
//   bits [31:21] = reserved / sequence counter
#define ADC16_RESULT_MASK 0x0000FFFFu

// Number of ADC inputs used in this build (raw inputs only for now)
#define ADC_TOTAL_INPUTS (ADC_NUM_RAW_INPUTS)

// DMA buffer: one 32-bit word per ADC channel per conversion
__attribute__((aligned(8)))
ATTR_NONCACHEABLE
static volatile uint32_t adc_dma_buf[ADC_TOTAL_INPUTS];

// Processed 16-bit results indexed by key number
static volatile uint16_t adc_values[NUM_KEYS];

// Set to true once the first DMA transfer completes
static volatile bool adc_initialized = false;

// Raw input channel list (generated by make_cmake.py from keyboard.json)
static const uint8_t raw_input_channels[] = ADC_RAW_INPUT_CHANNELS;
static const uint16_t raw_input_vector[]  = ADC_RAW_INPUT_VECTOR;

// --------------------------------------------------------------------
// ADC GPIO / IOC Pin Setup
//
// HPM ADC pins require IOC mode set to ADC function (no pull-up/down).
// IOC pad indices must match the channel-to-pin table in the datasheet.
// --------------------------------------------------------------------

// Map ADC global channel index to IOC pad index.
// NOTE: Verify this table against HPM5361 pin multiplex table.
static const uint16_t adc_ioc_pads[] = {
    // ADC0 CH0-15: PA00-PA07, PB00-PB07
    IOC_PAD_PA00, IOC_PAD_PA01, IOC_PAD_PA02, IOC_PAD_PA03,
    IOC_PAD_PA04, IOC_PAD_PA05, IOC_PAD_PA06, IOC_PAD_PA07,
    IOC_PAD_PB00, IOC_PAD_PB01, IOC_PAD_PB02, IOC_PAD_PB03,
    IOC_PAD_PB04, IOC_PAD_PB05, IOC_PAD_PB06, IOC_PAD_PB07,
    // ADC1 CH0-15: PC00-PC07, PD00-PD07
    IOC_PAD_PC00, IOC_PAD_PC01, IOC_PAD_PC02, IOC_PAD_PC03,
    IOC_PAD_PC04, IOC_PAD_PC05, IOC_PAD_PC06, IOC_PAD_PC07,
    IOC_PAD_PD00, IOC_PAD_PD01, IOC_PAD_PD02, IOC_PAD_PD03,
    IOC_PAD_PD04, IOC_PAD_PD05, IOC_PAD_PD06, IOC_PAD_PD07,
};

static void adc_configure_pin(uint8_t global_ch) {
  uint16_t pad = adc_ioc_pads[global_ch];
  // Set pad to analog input mode (no pull, no Schmitt)
  HPM_IOC->PAD[pad].FUNC_CTL = IOC_PAD_FUNC_CTL_ANALOG_MASK;
  HPM_IOC->PAD[pad].PAD_CTL  = 0;
}

// --------------------------------------------------------------------
// DMA Setup
// --------------------------------------------------------------------

static void adc_dma_init(void) {
  // Use DMA0 channel 0 for ADC0 sequence results
  clock_add_to_group(clock_dma0, 0);

  dma_channel_config_t ch_cfg;
  dma_default_channel_config(HPM_DMA0, &ch_cfg);

  // Source: ADM ADC0 sequence result buffer (peripheral FIFO)
  // The ADC16 sequence stores results at ADC->SEQ_DMA_ADDR (check SDK)
  ch_cfg.src_addr  = (uint32_t)&HPM_ADC0->ADC_DMA_RD; // TODO: verify register name
  ch_cfg.dst_addr  = core_local_mem_to_sys_address(BOARD_RUNNING_CORE,
                         (uint32_t)adc_dma_buf);
  ch_cfg.src_width = DMA_TRANSFER_WIDTH_WORD;
  ch_cfg.dst_width = DMA_TRANSFER_WIDTH_WORD;
  ch_cfg.size_in_byte = sizeof(uint32_t) * ADC_TOTAL_INPUTS;
  ch_cfg.src_mode  = DMA_HANDSHAKE_MODE_HANDSHAKE;
  ch_cfg.dst_mode  = DMA_HANDSHAKE_MODE_NORMAL;
  ch_cfg.src_burst_size = DMA_NUM_TRANSFER_PER_BURST_1T;
  ch_cfg.en_dmamux = true;
  ch_cfg.dmamux_src = HPM_DMA_SRC_ADC0_SEQ; // TODO: verify DMAMUX source ID
  ch_cfg.complete_int_en = true;

  dma_setup_channel(HPM_DMA0, 0, &ch_cfg, true);

  intc_m_enable_irq_with_priority(IRQn_DMA0, 1);
}

// --------------------------------------------------------------------
// ADC Sequence Init
// --------------------------------------------------------------------

static void adc_seq_init(ADC16_Type *adc, const uint8_t *channels,
                         uint32_t count) {
  // Configure ADC16 base
  adc16_config_t cfg;
  adc16_get_default_config(&cfg);
  cfg.res         = adc16_res_16_bits;
  cfg.conv_mode   = adc16_conv_mode_sequence;
  cfg.clock_divider = 2; // ADC clock = core clock / 2; adjust for timing
  adc16_init(adc, &cfg);

  // Configure each channel with 16x hardware averaging
  for (uint32_t i = 0; i < count; i++) {
    adc16_channel_config_t ch_cfg;
    adc16_get_channel_default_config(&ch_cfg);
    ch_cfg.ch           = channels[i];
    ch_cfg.sample_cycle = 20; // Sample cycles; adjust for sensor settling time
    ch_cfg.average_mode = adc16_average_16; // 16x hardware oversampling
    ch_cfg.wdog_en      = false;
    adc16_init_channel(adc, &ch_cfg);
  }

  // Configure sequence queue
  adc16_seq_config_t seq_cfg;
  memset(&seq_cfg, 0, sizeof(seq_cfg));
  for (uint32_t i = 0; i < count; i++) {
    seq_cfg.queue[i].ch = channels[i];
    seq_cfg.queue[i].seq_int_en = (i == count - 1); // Interrupt on last ch
  }
  seq_cfg.queue_len   = count;
  seq_cfg.restart_en  = false;
  seq_cfg.cont_en     = false; // One-shot per software trigger
  seq_cfg.sw_trig_en  = true;
  seq_cfg.hw_trig_en  = false;
  adc16_set_seq_config(adc, &seq_cfg);

  // Enable sequence DMA
  adc16_dma_config_t dma_cfg = {
      .start_addr         = core_local_mem_to_sys_address(BOARD_RUNNING_CORE,
                                (uint32_t)adc_dma_buf),
      .buff_len_in_4bytes = count,
      .stop_en            = false,
      .stop_pos           = 0,
  };
  adc16_init_seq_dma(adc, &dma_cfg);

  // Enable ADC clock group
  clock_add_to_group(clock_adc0, 0);
}

// --------------------------------------------------------------------
// Analog API
// --------------------------------------------------------------------

void analog_init(void) {
  // Configure ADC GPIO pins
  for (uint32_t i = 0; i < ADC_TOTAL_INPUTS; i++) {
    adc_configure_pin(raw_input_channels[i]);
  }

  // Build a local-channel list for ADC0 (channels < 16)
  // Multi-ADC support (ADC1) can be added later as needed
  uint8_t local_channels[ADC_TOTAL_INPUTS];
  for (uint32_t i = 0; i < ADC_TOTAL_INPUTS; i++) {
    local_channels[i] = HPM_ADC_LOCAL_CH(raw_input_channels[i]);
  }

  adc_seq_init(HPM_ADC0, local_channels, ADC_TOTAL_INPUTS);
  adc_dma_init();

  // Fire the first software trigger to start the conversion loop
  adc16_trigger_seq_by_sw(HPM_ADC0);

  // Wait for the first DMA transfer to complete
  while (!adc_initialized);
}

void analog_task(void) {
  // DMA transfers results continuously; no polling needed here.
  // The DMA ISR retriggers the ADC after each completed sequence.
}

uint16_t analog_read(uint8_t key) { return adc_values[key]; }

// --------------------------------------------------------------------
// Interrupt Handlers
// --------------------------------------------------------------------

SDK_DECLARE_EXT_ISR_M(IRQn_DMA0, isr_dma0)
void isr_dma0(void) {
  volatile uint32_t s = HPM_DMA0->INTSTATUS;
  HPM_DMA0->INTSTATUS = s; // Clear flags

  if (s & (1u << 0)) { // Channel 0 complete
    // Invalidate cache to ensure we read DMA-written data (NONCACHEABLE buf,
    // so this is mainly a compiler barrier; kept for safety on cached variants)
    for (uint32_t i = 0; i < ADC_TOTAL_INPUTS; i++) {
      uint16_t key = raw_input_vector[i];
      if (key > 0 && key <= NUM_KEYS)
        adc_values[key - 1] = (uint16_t)(adc_dma_buf[i] & ADC16_RESULT_MASK);
    }

    adc_initialized = true;

    // Re-trigger ADC for next conversion cycle
    adc16_trigger_seq_by_sw(HPM_ADC0);
  }
}
